/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.outros;

import com.mycompany.ferramentas.BancoDeDadosMySql;
import com.mycompany.visao.categoria.CadCategoria;
import com.mycompany.visao.categoria.ListCategoria;
import com.mycompany.visao.pais.CadPais;
import com.mycompany.visao.pais.ListPais;
import javax.swing.JOptionPane;

/**
 *
 * @author leonardo.35903
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if(!BancoDeDadosMySql.conectar()){
            JOptionPane.showMessageDialog(null,"Não foi possivel conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroPais = new javax.swing.JMenuItem();
        miCadastroEstado = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsultaCategoria = new javax.swing.JMenuItem();
        miConsultaPais = new javax.swing.JMenuItem();
        miConsultaEstado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setText("Cadastros");

        miCadastroCategoria.setText("Categoria");
        miCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCategoriaActionPerformed(evt);
            }
        });
        menuBar.add(miCadastroCategoria);

        miCadastroPais.setText("Pais");
        miCadastroPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPaisActionPerformed(evt);
            }
        });
        menuBar.add(miCadastroPais);

        miCadastroEstado.setText("Estado");
        menuBar.add(miCadastroEstado);

        jMenuBar1.add(menuBar);

        jMenu2.setText("Consultas");

        miConsultaCategoria.setText("Categoria");
        miConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaCategoria);

        miConsultaPais.setText("Pais");
        miConsultaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPaisActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaPais);

        miConsultaEstado.setText("Estado");
        jMenu2.add(miConsultaEstado);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCategoriaActionPerformed
        // TODO add your handling code here:
        CadCategoria cadcategoria = new CadCategoria();
        cadcategoria.setVisible(true);
        
    }//GEN-LAST:event_miCadastroCategoriaActionPerformed

    private void miConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCategoriaActionPerformed
        // TODO add your handling code here:
        ListCategoria listcategoria = new ListCategoria();
        listcategoria.setVisible(true);
    }//GEN-LAST:event_miConsultaCategoriaActionPerformed

    private void miCadastroPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPaisActionPerformed
        // TODO add your handling code here:
        CadPais cadpais = new CadPais();
        cadpais.setVisible(true);
    }//GEN-LAST:event_miCadastroPaisActionPerformed

    private void miConsultaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPaisActionPerformed
        // TODO add your handling code here:
        ListPais listPais = new ListPais();
        listPais.setVisible(true);
    }//GEN-LAST:event_miConsultaPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuBar;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroEstado;
    private javax.swing.JMenuItem miCadastroPais;
    private javax.swing.JMenuItem miConsultaCategoria;
    private javax.swing.JMenuItem miConsultaEstado;
    private javax.swing.JMenuItem miConsultaPais;
    // End of variables declaration//GEN-END:variables
}
